In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
import joblib
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
team_stat_df = pd.read_csv(
    Path("team_stats_merge_4.csv")
)

# Review the DataFrame
display(team_stat_df.head())
display(team_stat_df.tail())

team_stat_id  team_id  season_id  team_stats_gamesPlayed  team_stats_wins  \
0           NaN        1   19911992                      80               38   
1           NaN        1   19921993                      84               40   
2           NaN        1   19931994                      84               47   
3           NaN        1   19941995                      48               22   
4           NaN        1   19951996                      82               37   

   team_stats_losses  team_stats_ot  team_stats_pts  team_stats_ptPctg  \
0                 31              0              87               54.4   
1                 37              0              87               51.8   
2                 25              0             106               63.1   
3                 18              0              52               54.2   
4                 33              0              86               52.4   

   team_stats_goalsPerGame  ...  team_stats_shotsAllowed  \
0                    3.613  ...                  28.6250   
1                    3.667  ...                  29.8095   
2                    3.643  ...                  29.0119   
3                    2.833  ...                  25.3750   
4                    2.622  ...                  26.5000   

   team_stats_winScoreFirst  team_stats_winOppScoreFirst  \
0                     0.711                        0.262   
1                     0.641                        0.333   
2                     0.717                        0.368   
3                     0.600                        0.304   
4                     0.643                        0.250   

   team_stats_winLeadFirstPer  team_stats_winLeadSecondPer  \
0                       0.793                        0.805   
1                       0.769                        0.838   
2                       0.897                        0.921   
3                       0.667                        0.714   
4                       0.677                        0.774   

   team_stats_winOutshootOpp  team_stats_winOutshotByOpp          team_name  \
0                      0.490                       0.414  New Jersey Devils   
1                      0.510                       0.452  New Jersey Devils   
2                      0.607                       0.444  New Jersey Devils   
3                      0.533                       0.313  New Jersey Devils   
4                      0.475                       0.381  New Jersey Devils   

   team_location  winning_team  
0     New Jersey             0  
1     New Jersey             0  
2     New Jersey             0  
3     New Jersey             1  
4     New Jersey             0  

[5 rows x 28 columns]

team_stat_id  team_id  season_id  team_stats_gamesPlayed  \
849           NaN       54   20202021                      56   
850           NaN       54   20212022                      82   
851           NaN       54   20222023                      82   
852           NaN       55   20212022                      82   
853           NaN       55   20222023                      82   

     team_stats_wins  team_stats_losses  team_stats_ot  team_stats_pts  \
849               40                 14              2              82   
850               43                 31              8              94   
851               51                 22              9             111   
852               27                 49              6              60   
853               46                 28              8             100   

     team_stats_ptPctg  team_stats_goalsPerGame  ...  team_stats_shotsAllowed  \
849               73.2                   3.3930  ...                  27.2679   
850               57.3                   3.1950  ...                  29.9756   
851               67.7                   3.2561  ...                  30.8902   
852               36.6                   2.5980  ...                  28.8659   
853               61.0                   3.5244  ...                  27.0122   

     team_stats_winScoreFirst  team_stats_winOppScoreFirst  \
849                     0.861                        0.450   
850                     0.689                        0.324   
851                     0.826                        0.361   
852                     0.484                        0.235   
853                     0.762                        0.350   

     team_stats_winLeadFirstPer  team_stats_winLeadSecondPer  \
849                       0.846                        0.931   
850                       0.759                        0.886   
851                       0.857                        0.919   
852                       0.619                        0.739   
853                       0.862                        0.897   

     team_stats_winOutshootOpp  team_stats_winOutshotByOpp  \
849                      0.769                       0.667   
850                      0.500                       0.545   
851                      0.692                       0.541   
852                      0.410                       0.231   
853                      0.600                       0.458   

                team_name  team_location  winning_team  
849  Vegas Golden Knights          Vegas             0  
850  Vegas Golden Knights          Vegas             0  
851  Vegas Golden Knights          Vegas             1  
852        Seattle Kraken        Seattle             0  
853        Seattle Kraken        Seattle             0  

[5 rows x 28 columns]

In [3]:
# Removed the columns are not applicable to train the model
clean_team_stat_df =team_stat_df.drop(columns=['team_stat_id','team_id','season_id'])
clean_team_stat_df.head()

team_stats_gamesPlayed  team_stats_wins  team_stats_losses  team_stats_ot  \
0                      80               38                 31              0   
1                      84               40                 37              0   
2                      84               47                 25              0   
3                      48               22                 18              0   
4                      82               37                 33              0   

   team_stats_pts  team_stats_ptPctg  team_stats_goalsPerGame  \
0              87               54.4                    3.613   
1              87               51.8                    3.667   
2             106               63.1                    3.643   
3              52               54.2                    2.833   
4              86               52.4                    2.622   

   team_stats_goalsAgainstPerGame  team_stats_evGGARatio  \
0                           3.238                 1.2314   
1                           3.560                 1.2314   
2                           2.619                 0.7616   
3                           2.521                 0.7616   
4                           2.463                 1.0000   

   team_stats_powerPlayPercentage  ...  team_stats_shotsAllowed  \
0                            17.5  ...                  28.6250   
1                            19.2  ...                  29.8095   
2                            18.3  ...                  29.0119   
3                            13.4  ...                  25.3750   
4                            14.9  ...                  26.5000   

   team_stats_winScoreFirst  team_stats_winOppScoreFirst  \
0                     0.711                        0.262   
1                     0.641                        0.333   
2                     0.717                        0.368   
3                     0.600                        0.304   
4                     0.643                        0.250   

   team_stats_winLeadFirstPer  team_stats_winLeadSecondPer  \
0                       0.793                        0.805   
1                       0.769                        0.838   
2                       0.897                        0.921   
3                       0.667                        0.714   
4                       0.677                        0.774   

   team_stats_winOutshootOpp  team_stats_winOutshotByOpp          team_name  \
0                      0.490                       0.414  New Jersey Devils   
1                      0.510                       0.452  New Jersey Devils   
2                      0.607                       0.444  New Jersey Devils   
3                      0.533                       0.313  New Jersey Devils   
4                      0.475                       0.381  New Jersey Devils   

   team_location  winning_team  
0     New Jersey             0  
1     New Jersey             0  
2     New Jersey             0  
3     New Jersey             1  
4     New Jersey             0  

[5 rows x 25 columns]

In [4]:
# Create dummy columns for categorical data
final_team_stat_df = pd.get_dummies(clean_team_stat_df , columns=['team_name','team_location'])
final_team_stat_df.head() 

team_stats_gamesPlayed  team_stats_wins  team_stats_losses  team_stats_ot  \
0                      80               38                 31              0   
1                      84               40                 37              0   
2                      84               47                 25              0   
3                      48               22                 18              0   
4                      82               37                 33              0   

   team_stats_pts  team_stats_ptPctg  team_stats_goalsPerGame  \
0              87               54.4                    3.613   
1              87               51.8                    3.667   
2             106               63.1                    3.643   
3              52               54.2                    2.833   
4              86               52.4                    2.622   

   team_stats_goalsAgainstPerGame  team_stats_evGGARatio  \
0                           3.238                 1.2314   
1                           3.560                 1.2314   
2                           2.619                 0.7616   
3                           2.521                 0.7616   
4                           2.463                 1.0000   

   team_stats_powerPlayPercentage  ...  team_location_Pittsburgh  \
0                            17.5  ...                         0   
1                            19.2  ...                         0   
2                            18.3  ...                         0   
3                            13.4  ...                         0   
4                            14.9  ...                         0   

   team_location_San Jose  team_location_Seattle  team_location_St. Louis  \
0                       0                      0                        0   
1                       0                      0                        0   
2                       0                      0                        0   
3                       0                      0                        0   
4                       0                      0                        0   

   team_location_Tampa Bay  team_location_Toronto  team_location_Vancouver  \
0                        0                      0                        0   
1                        0                      0                        0   
2                        0                      0                        0   
3                        0                      0                        0   
4                        0                      0                        0   

   team_location_Vegas  team_location_Washington  team_location_Winnipeg  
0                    0                         0                       0  
1                    0                         0                       0  
2                    0                         0                       0  
3                    0                         0                       0  
4                    0                         0                       0  

[5 rows x 86 columns]

Logostic Regression Model with Imbalance Data

In [7]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = final_team_stat_df ['winning_team']

# Separate the X variable, the features
X = final_team_stat_df .drop(columns=['winning_team'])

In [8]:
# Check the balance of our target values
y.value_counts()

0    823
1     31
Name: winning_team, dtype: int64

In [9]:
# Import the train_test_learn module LogisticRegression
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False,random_state=1)
# Assign a random_state of 1 to the function
from sklearn.linear_model import LogisticRegression
logistic_regression_model = LogisticRegression(random_state=1)

In [10]:
# Fit the model using training data
lr_model = logistic_regression_model.fit(X_train, y_train)

c:\Users\User\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
# Make a prediction using the testing data
#Generate training predictions
training_predictions = lr_model.predict(X_train)
#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [12]:
# Print the balanced_accuracy score of the model
logistic_score = balanced_accuracy_score(y_test, testing_predictions)
logistic_score

0.5

In [13]:
# Generate a confusion matrix for the model
# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)
print(f'the confusion matrix for the training data')
print(training_matrix)
# Create and save the confusion matrix for the testing data

test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(f'the confusion matrix for the test data')
print(test_matrix)

the confusion matrix for the training data
[[611   3]
 [ 26   0]]
the confusion matrix for the test data
[[209   0]
 [  5   0]]


In [14]:
# Print the classification report for the model
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       614
           1       0.00      0.00      0.00        26

    accuracy                           0.95       640
   macro avg       0.48      0.50      0.49       640
weighted avg       0.92      0.95      0.94       640



In [15]:
# Save the model into the folder
logisticRegression = "Models_NHL/logisticRegression.pkl"
joblib.dump(lr_model, logisticRegression)

['Models_NHL/logisticRegression.pkl']

RandomOverSampler to balance the data and logistic Regression Model

In [16]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
x_res, y_res = ros.fit_resample(X_train, y_train)

In [17]:
# Count the distinct values of the resampled labels data
# Balanced Data
y_res.value_counts()

0    614
1    614
Name: winning_team, dtype: int64

In [18]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier = LogisticRegression(solver='lbfgs', random_state=1)

# Fit the model using the resampled training data
classifier.fit(x_res, y_res)
# Make a prediction using the testing data
predictions = classifier.predict(X_test)

c:\Users\User\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
# Print the balanced_accuracy score of the model 
predicted_log_score = balanced_accuracy_score(y_test, predictions)
predicted_log_score

0.6449760765550239

In [20]:
# Generate a confusion matrix for the model
predicted_log_matrix = confusion_matrix(y_test, predictions)
predicted_log_matrix

array([[186,  23],
       [  3,   2]], dtype=int64)

In [21]:
# Print the classification report for the model
predicted_log_report = classification_report(y_test, predictions)
print(predicted_log_report)

              precision    recall  f1-score   support

           0       0.98      0.89      0.93       209
           1       0.08      0.40      0.13         5

    accuracy                           0.88       214
   macro avg       0.53      0.64      0.53       214
weighted avg       0.96      0.88      0.92       214



In [58]:
# Save the model into the folder
logisticRegression_ROS = "Models_NHL/logisticRegression_ROS.pkl"
joblib.dump(classifier, logisticRegression_ROS)

['Models_NHL/logisticRegression_ROS.pkl']

RandomOverSampler to balance the data and DecisionTreeClassifier Model

In [23]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(x_res, y_res, random_state=42)

In [24]:
# Create the decision tree classifier
#clf = DecisionTreeClassifier(criterion='gini',class_weight={0:0.13,1:0.83},random_state=42)
clf = DecisionTreeClassifier(random_state=42)
# Train the classifier on the training data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [25]:

DCTree_predicted_log_matrix = confusion_matrix(y_test, y_pred)
DCTree_predicted_log_matrix

array([[146,   7],
       [  0, 154]], dtype=int64)

In [26]:
DCTree_predicted_log_report = classification_report(y_test, y_pred)
print(DCTree_predicted_log_report)

              precision    recall  f1-score   support

           0       1.00      0.95      0.98       153
           1       0.96      1.00      0.98       154

    accuracy                           0.98       307
   macro avg       0.98      0.98      0.98       307
weighted avg       0.98      0.98      0.98       307



In [59]:
# Save the model into the folder
DCTree_ROS = "Models_NHL/DCTree_ROS.pkl"
joblib.dump(clf, DCTree_ROS)

['Models_NHL/DCTree_ROS.pkl']

RandomOverSampler to balance the data and DecisionTreeClassifier Model with class Weight

In [28]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(x_res, y_res, random_state=42)

In [29]:
# Create the decision tree classifier
clf = DecisionTreeClassifier(criterion='gini',class_weight={0:0.13,1:0.83},random_state=42)
# Train the classifier on the training data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [30]:
DCTreeW_predicted_log_matrix = confusion_matrix(y_test, y_pred)
DCTreeW_predicted_log_matrix

array([[149,   4],
       [  0, 154]], dtype=int64)

In [31]:
DCTreeW_predicted_log_report = classification_report(y_test, y_pred)
print(DCTreeW_predicted_log_report)

              precision    recall  f1-score   support

           0       1.00      0.97      0.99       153
           1       0.97      1.00      0.99       154

    accuracy                           0.99       307
   macro avg       0.99      0.99      0.99       307
weighted avg       0.99      0.99      0.99       307



Optimized Model

In [60]:
# Save the model into the folder
DCTreeCW_ROS = "Models_NHL/DCTreeCW_ROS.pkl"
joblib.dump(clf, DCTreeCW_ROS)

['Models_NHL/DCTreeCW_ROS.pkl']

Under Sampling with DCTree Model

In [33]:
# Option1 Under sampling
# value count of winning and losing data
losing_team_stat_count,winning_team_stat_count =final_team_stat_df.winning_team.value_counts()

df_winning_team_stat=final_team_stat_df[final_team_stat_df['winning_team']==1]
df_losing_team_stat=final_team_stat_df[final_team_stat_df['winning_team']==0]

In [34]:
# Verify the count of losing data
df_losing_team_stat.shape

(823, 86)

In [35]:
# Verify the count of winning data
df_winning_team_stat.shape


(31, 86)

In [36]:
#create under sample losing data
df_losing_team_stat_underCount= df_losing_team_stat.sample(winning_team_stat_count)
df_losing_team_stat_underCount.head()

team_stats_gamesPlayed  team_stats_wins  team_stats_losses  \
852                      82               27                 49   
234                      82               39                 33   
786                      82               33                 42   
319                      82               45                 30   
168                      82               29                 37   

     team_stats_ot  team_stats_pts  team_stats_ptPctg  \
852              6              60               36.6   
234             10              88               53.7   
786              7              73               44.5   
319              7              97               59.1   
168             16              74               45.1   

     team_stats_goalsPerGame  team_stats_goalsAgainstPerGame  \
852                    2.598                           3.463   
234                    2.561                           2.659   
786                    2.390                           2.976   
319                    2.878                           2.695   
168                    2.780                           3.146   

     team_stats_evGGARatio  team_stats_powerPlayPercentage  ...  \
852                 0.8042                            14.6  ...   
234                 0.9041                            21.8  ...   
786                 0.8496                            14.8  ...   
319                 1.0000                            18.7  ...   
168                 0.9412                            14.8  ...   

     team_location_Pittsburgh  team_location_San Jose  team_location_Seattle  \
852                         0                       0                      1   
234                         0                       0                      0   
786                         0                       0                      0   
319                         0                       0                      0   
168                         0                       0                      0   

     team_location_St. Louis  team_location_Tampa Bay  team_location_Toronto  \
852                        0                        0                      0   
234                        0                        0                      0   
786                        0                        0                      0   
319                        0                        0                      0   
168                        0                        0                      0   

     team_location_Vancouver  team_location_Vegas  team_location_Washington  \
852                        0                    0                         0   
234                        0                    0                         0   
786                        0                    0                         0   
319                        0                    0                         0   
168                        0                    0                         0   

     team_location_Winnipeg  
852                       0  
234                       0  
786                       0  
319                       0  
168                       0  

[5 rows x 86 columns]

In [37]:
#contact two winning and losing team dataframe with total 62 rows
UnderCount_df=pd.concat([df_losing_team_stat_underCount,df_winning_team_stat],axis =0)
print("random under sample")
print(UnderCount_df.winning_team.value_counts())

random under sample
0    31
1    31
Name: winning_team, dtype: int64


In [38]:

# Separate the y variable, the labels
y = UnderCount_df ['winning_team']

# Separate the X variable, the features
X = UnderCount_df .drop(columns=['winning_team'])

In [39]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

# Create the decision tree classifier
clf = DecisionTreeClassifier(criterion='gini',class_weight={0:0.13,1:0.83},random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [40]:
underCount_matrix = confusion_matrix(y_test, y_pred)
underCount_matrix

array([[7, 0],
       [2, 4]], dtype=int64)

In [41]:
UnderCount_report = classification_report(y_test, y_pred)
print(UnderCount_report)

              precision    recall  f1-score   support

           0       0.78      1.00      0.88         7
           1       1.00      0.67      0.80         6

    accuracy                           0.85        13
   macro avg       0.89      0.83      0.84        13
weighted avg       0.88      0.85      0.84        13



In [61]:
# Save the model into the folder
DCTreeCW_US = "Models_NHL/DCTreeCW_US.pkl"
joblib.dump(clf, DCTreeCW_US)

['Models_NHL/DCTreeCW_US.pkl']

Over Sampling with DCTree Model

In [43]:
# Option1 Over sampling
losing_team_stat_count,winning_team_stat_count

(823, 31)

In [44]:
#create over sample winning data
df_winning_team_stat_OverCount= df_winning_team_stat.sample(losing_team_stat_count,replace=True)
df_winning_team_stat_OverCount.head()

team_stats_gamesPlayed  team_stats_wins  team_stats_losses  \
3                        48               22                 18   
536                      82               45                 28   
64                       84               52                 24   
738                      82               40                 27   
444                      48               36                  7   

     team_stats_ot  team_stats_pts  team_stats_ptPctg  \
3                0              52               54.2   
536              9              99               60.4   
64               0             112               66.7   
738             15              95               57.9   
444              5              77               80.2   

     team_stats_goalsPerGame  team_stats_goalsAgainstPerGame  \
3                      2.833                           2.521   
536                    2.976                           2.683   
64                     3.560                           2.750   
738                    2.293                           2.073   
444                    3.104                           2.021   

     team_stats_evGGARatio  team_stats_powerPlayPercentage  ...  \
3                   0.7616                            13.4  ...   
536                 1.1361                            21.1  ...   
64                  0.7468                            23.0  ...   
738                 0.9752                            17.0  ...   
444                 1.5211                            16.7  ...   

     team_location_Pittsburgh  team_location_San Jose  team_location_Seattle  \
3                           0                       0                      0   
536                         0                       0                      0   
64                          0                       0                      0   
738                         0                       0                      0   
444                         0                       0                      0   

     team_location_St. Louis  team_location_Tampa Bay  team_location_Toronto  \
3                          0                        0                      0   
536                        1                        0                      0   
64                         0                        0                      0   
738                        0                        0                      0   
444                        0                        0                      0   

     team_location_Vancouver  team_location_Vegas  team_location_Washington  \
3                          0                    0                         0   
536                        0                    0                         0   
64                         0                    0                         0   
738                        0                    0                         0   
444                        0                    0                         0   

     team_location_Winnipeg  
3                         0  
536                       0  
64                        0  
738                       0  
444                       0  

[5 rows x 86 columns]

In [45]:
#contact two winning and losing team dataframe with total 1646 rows
OverCount_df=pd.concat([df_winning_team_stat_OverCount,df_losing_team_stat],axis =0)
print("random over sample")
print(OverCount_df.winning_team.value_counts())

random over sample
1    823
0    823
Name: winning_team, dtype: int64


In [46]:

# Separate the y variable, the labels
y = OverCount_df ['winning_team']

# Separate the X variable, the features
X = OverCount_df .drop(columns=['winning_team'])

In [47]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

# Create the decision tree classifier
clf = DecisionTreeClassifier(criterion='gini',class_weight={0:0.13,1:0.83},random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [48]:
OverCount_matrix = confusion_matrix(y_test, y_pred)
OverCount_matrix

array([[157,   8],
       [  0, 165]], dtype=int64)

In [49]:
OverCount_report = classification_report(y_test, y_pred)
print(OverCount_report)

              precision    recall  f1-score   support

           0       1.00      0.95      0.98       165
           1       0.95      1.00      0.98       165

    accuracy                           0.98       330
   macro avg       0.98      0.98      0.98       330
weighted avg       0.98      0.98      0.98       330



In [62]:
# Save the model into the folder
DCTreeCW_OS = "Models_NHL/DCTreeCW_OS.pkl"
joblib.dump(clf, DCTreeCW_OS)

['Models_NHL/DCTreeCW_OS.pkl']

SMOTE with DCTree Model

In [51]:
#Option3 SMOTE
# Separate the y variable, the labels
y = final_team_stat_df ['winning_team']

# Separate the X variable, the features
X = final_team_stat_df.drop(columns=['winning_team'])

In [52]:
y.value_counts()

0    823
1     31
Name: winning_team, dtype: int64

In [53]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_sm,y_sm=smote.fit_resample(X,y)
y_sm.value_counts()

0    823
1    823
Name: winning_team, dtype: int64

In [54]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(X_sm,y_sm, test_size=0.2, random_state=42)

# Create the decision tree classifier
clf = DecisionTreeClassifier(criterion='gini',class_weight={0:0.13,1:0.83},random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [55]:
SMOTE_matrix = confusion_matrix(y_test, y_pred)
SMOTE_matrix

array([[167,   5],
       [  5, 153]], dtype=int64)

In [56]:
SMOTE_report = classification_report(y_test, y_pred)
print(SMOTE_report)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       172
           1       0.97      0.97      0.97       158

    accuracy                           0.97       330
   macro avg       0.97      0.97      0.97       330
weighted avg       0.97      0.97      0.97       330



In [57]:
# Save the model into the folder

DCTreeCW_SMOTE = "Models_NHL/DCTreeCW_SMOTE.pkl"
joblib.dump(clf,DCTreeCW_SMOTE)



['Models_NHL/DCTreeCW_SMOTE.pkl']

In [63]:
import joblib
import numpy as np
import pandas as pd

# Load the saved model from the .pkl file
# Replace 'your_model.pkl' with the actual path to your saved model file
loaded_model = joblib.load('Models_NHL/DCTreeCW_ROS.pkl')

# Create a DataFrame with the same columns as used during training
# Include all features, including one-hot encoded team names and team locations
new_game_data = pd.DataFrame({
    'team_stats_gamesPlayed': [82],
    'team_stats_wins': [51],
    'team_stats_losses': [22],
    'team_stats_ot': [9],
    'team_stats_pts': [111],
    'team_stats_ptPctg': [67.7],
    'team_stats_goalsPerGame': [3.2561],
    'team_stats_goalsAgainstPerGame': [2.743902],
    'team_stats_evGGARatio': [1.1761],
    'team_stats_powerPlayPercentage': [20.3],
    'team_stats_powerPlayGoals': [42],
    'team_stats_powerPlayGoalsAgainst': [44],
    'team_stats_powerPlayOpportunities': [207],
    'team_stats_penaltyKillPercentage': [77.4],
    'team_stats_shotsPerGame': [31.5488],
    'team_stats_shotsAllowed': [30.8902],
    'team_stats_winScoreFirst': [0.826],
    'team_stats_winOppScoreFirst': [0.361],
    'team_stats_winLeadFirstPer': [0.857],
    'team_stats_winLeadSecondPer': [0.919],
    'team_stats_winOutshootOpp': [0.692],
    'team_stats_winOutshotByOpp': [0.541],
    'team_name_Anaheim Ducks': [0], 
    'team_name_Arizona Coyotes': [0],
    'team_name_Boston Bruins': [0],
    'team_name_Buffalo Sabres': [0], 
    'team_name_Calgary Flames': [0], 
    'team_name_Carolina Hurricanes': [0], 
    'team_name_Chicago Blackhawks': [0], 
    'team_name_Colorado Avalanche': [0], 
    'team_name_Columbus Blue Jackets': [0], 
    'team_name_Dallas Stars': [0], 
    'team_name_Detroit Red Wings': [0], 
    'team_name_Edmonton Oilers': [0], 
    'team_name_Florida Panthers': [0], 
    'team_name_Los Angeles Kings': [0],
    'team_name_Minnesota Wild': [0], 
    'team_name_Montréal Canadiens': [0], 
    'team_name_Nashville Predators': [0], 
    'team_name_New Jersey Devils': [0], 
    'team_name_New York Islanders': [0], 
    'team_name_New York Rangers': [0], 
    'team_name_Ottawa Senators': [0], 
    'team_name_Philadelphia Flyers': [0], 
    'team_name_Pittsburgh Penguins': [0], 
    'team_name_San Jose Sharks': [0], 
    'team_name_Seattle Kraken': [0], 
    'team_name_St. Louis Blues': [0], 
    'team_name_Tampa Bay Lightning': [0], 
    'team_name_Toronto Maple Leafs': [0], 
    'team_name_Vancouver Canucks': [0], 
    'team_name_Vegas Golden Knights': [1], 
    'team_name_Washington Capitals': [0], 
    'team_name_Winnipeg Jets': [0], 
    'team_location_Anaheim': [0], 
    'team_location_Arizona': [0], 
    'team_location_Boston': [0], 
    'team_location_Buffalo': [0], 
    'team_location_Calgary': [0], 
    'team_location_Carolina': [0], 
    'team_location_Chicago': [0], 
    'team_location_Colorado': [0], 
    'team_location_Columbus': [0], 
    'team_location_Dallas': [0], 
    'team_location_Detroit': [0], 
    'team_location_Edmonton': [0], 
    'team_location_Florida': [0], 
    'team_location_Los Angeles': [0], 
    'team_location_Minnesota': [0], 
    'team_location_Montréal': [0], 
    'team_location_Nashville': [0], 
    'team_location_New Jersey': [0], 
    'team_location_New York': [0], 
    'team_location_Ottawa': [0], 
    'team_location_Philadelphia': [0], 
    'team_location_Pittsburgh': [0], 
    'team_location_San Jose': [0], 
    'team_location_Seattle': [0], 
    'team_location_St. Louis': [0], 
    'team_location_Tampa Bay': [0], 
    'team_location_Toronto': [0], 
    'team_location_Vancouver': [0], 
    'team_location_Vegas': [1], 
    'team_location_Washington': [0], 
    'team_location_Winnipeg': [0]


})

# Predict the probability of each class (team winning or losing)
predicted_probabilities = loaded_model.predict_proba(new_game_data)

# Extract the probability of each team winning (class 1)
team_win_probabilities = predicted_probabilities[:, 1]

# Calculate the probability as a percentage
team_win_probabilities_percent = [prob * 100 for prob in team_win_probabilities]

# You can print or use these probabilities as needed
for i, team in enumerate(['Vegas Golden Knights']):
    print(f"Probability of {team} winning: {team_win_probabilities_percent[i]:.2f}%")



Probability of Vegas Golden Knights winning: 100.00%
